import { Match } from './../components/views/matchDetails/utils';
export const COUNTRIES = [
  "España",
  "Afganistán",
  "Albania",
  "Alemania",
  "Andorra",
  "Angola",
  "Antigua y Barbuda",
  "Arabia Saudita",
  "Argelia",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaiyán",
  "Bahamas",
  "Bangladés",
  "Barbados",
  "Baréin",
  "Bélgica",
  "Belice",
  "Benín",
  "Bielorrusia",
  "Birmania",
  "Bolivia",
  "Bosnia y Herzegovina",
  "Botsuana",
  "Brasil",
  "Brunéi",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Bután",
  "Cabo Verde",
  "Camboya",
  "Camerún",
  "Canadá",
  "Catar",
  "Chad",
  "Chile",
  "China",
  "Chipre",
  "Ciudad del Vaticano",
  "Colombia",
  "Comoras",
  "Corea del Norte",
  "Corea del Sur",
  "Costa de Marfil",
  "Costa Rica",
  "Croacia",
  "Cuba",
  "Dinamarca",
  "Dominica",
  "Ecuador",
  "Egipto",
  "El Salvador",
  "Emiratos Árabes Unidos",
  "Eritrea",
  "Eslovaquia",
  "Eslovenia",
  "Estados Unidos",
  "Estonia",
  "Etiopía",
  "Filipinas",
  "Finlandia",
  "Fiyi",
  "Francia",
  "Gabón",
  "Gambia",
  "Georgia",
  "Ghana",
  "Granada",
  "Grecia",
  "Guatemala",
  "Guyana",
  "Guinea",
  "Guinea ecuatorial",
  "Guinea-Bisáu",
  "Haití",
  "Honduras",
  "Hungría",
  "India",
  "Indonesia",
  "Irak",
  "Irán",
  "Irlanda",
  "Islandia",
  "Islas Marshall",
  "Islas Salomón",
  "Israel",
  "Italia",
  "Jamaica",
  "Japón",
  "Jordania",
  "Kazajistán",
  "Kenia",
  "Kirguistán",
  "Kiribati",
  "Kuwait",
  "Laos",
  "Lesoto",
  "Letonia",
  "Líbano",
  "Liberia",
  "Libia",
  "Liechtenstein",
  "Lituania",
  "Luxemburgo",
  "Madagascar",
  "Malasia",
  "Malaui",
  "Maldivas",
  "Malí",
  "Malta",
  "Marruecos",
  "Mauricio",
  "Mauritania",
  "México",
  "Micronesia",
  "Moldavia",
  "Mónaco",
  "Mongolia",
  "Montenegro",
  "Mozambique",
  "Namibia",
  "Nauru",
  "Nepal",
  "Nicaragua",
  "Níger",
  "Nigeria",
  "Noruega",
  "Nueva Zelanda",
  "Omán",
  "Países Bajos",
  "Pakistán",
  "Palaos",
  "Palestina",
  "Panamá",
  "Papúa Nueva Guinea",
  "Paraguay",
  "Perú",
  "Polonia",
  "Portugal",
  "Reino Unido",
  "República Centroafricana",
  "República Checa",
  "República de Macedonia",
  "República del Congo",
  "República Democrática del Congo",
  "República Dominicana",
  "República Sudafricana",
  "Ruanda",
  "Rumanía",
  "Rusia",
  "Samoa",
  "San Cristóbal y Nieves",
  "San Marino",
  "San Vicente y las Granadinas",
  "Santa Lucía",
  "Santo Tomé y Príncipe",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leona",
  "Singapur",
  "Siria",
  "Somalia",
  "Sri Lanka",
  "Suazilandia",
  "Sudán",
  "Sudán del Sur",
  "Suecia",
  "Suiza",
  "Surinam",
  "Tailandia",
  "Tanzania",
  "Tayikistán",
  "Timor Oriental",
  "Togo",
  "Tonga",
  "Trinidad y Tobago",
  "Túnez",
  "Turkmenistán",
  "Turquía",
  "Tuvalu",
  "Ucrania",
  "Uganda",
  "Uruguay",
  "Uzbekistán",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Yibuti",
  "Zambia",
  "Zimbabue"
]

export const CCAA = [
  "Andalucia",
  "Aragón",
  "Canarias",
  "Cantabria",
  "Castilla y León",
  "Castilla-La Mancha",
  "Cataluña",
  "Ceuta",
  "Comunidad Valenciana",
  "Comunidad de Madrid",
  "Extremadura",
  "Galicia",
  "Islas Baleares",
  "La Rioja",
  "Melilla",
  "Navarra",
  "País Vasco",
  "Principado de Asturias",
  "Región de Murcia",
];

export const MATCHES: Match[] = [
  {
    status: 'No comenzado',
    local: {
      club: 'kjdlaksjdlsj',
      logo: 'https://res.cloudinary.com/dwta0wgpp/image/upload/v1645824762/asobal/1.svg',
      goals: [],
      cards: [],
      fouls: []
    },
    foreign: {
      club: 'kjdlaksjdlsj',
      logo: 'https://res.cloudinary.com/dwta0wgpp/image/upload/v1645824762/asobal/2.svg',
      goals: [],
      cards: [],
      fouls: []
    },
    date: '14:00',
    result: '1',
    id: '1212'
  },
  {
    status: 'Descanso',
    local: {
      club: 'kjdlaksjdlsj',
      logo: 'https://res.cloudinary.com/dwta0wgpp/image/upload/v1645824762/asobal/3.svg',
      goals: [3],
      cards: [
        {color: 'Amarilla', minute: 15},
        {color: 'Roja', minute: 23},
        {color: 'Azul', minute: 29}
      ],
      fouls: [1, 6, 22]
    },
    foreign: {
      club: 'kjdlaksjdlsj',
      logo: 'https://res.cloudinary.com/dwta0wgpp/image/upload/v1645824762/asobal/4.svg',
      goals: [10, 27],
      cards: [
        {color: 'Amarilla', minute: 15},
        {color: 'Roja', minute: 23},
        {color: 'Azul', minute: 29}
      ],
      fouls: [12, 15]
    },
    date: '14:00',
    result: '2',
    id: '1233'
  },
  {
    status: 'Terminado',
    local: {
      club: 'dsdasdasd121',
      logo: 'https://res.cloudinary.com/dwta0wgpp/image/upload/v1645824762/asobal/1.svg',
      goals: [],
      cards: [
        {color: 'Amarilla', minute: 8},
        {color: 'Amarilla', minute: 17},
        {color: 'Amarilla', minute: 21}
      ],
      fouls: [12, 16, 25]
    },
    foreign: {
      club: 'dsdasdasd121',
      logo: 'https://res.cloudinary.com/dwta0wgpp/image/upload/v1645824762/asobal/2.svg',
      goals: [],
      cards: [
        {color: 'Roja', minute: 20},
        {color: 'Amarilla', minute: 28}
      ],
      fouls: [1, 23]
    },
    date: '14:00',
    result: 'X',
    id: 'sdlasd'
  }
]